/**
 * This class has been generated by Fast Code Eclipse Plugin 
 * For more information please go to http://fast-code.sourceforge.net/
 * @author : jacky
 * Created : 08/26/2013
 */

package com.lodogame.ldsg.service;

import org.springframework.test.context.ContextConfiguration;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;

@ContextConfiguration(locations = { "classpath:applicationContext-test.xml" })
public class GoldSetServiceTest {

	@BeforeClass
	public void setUpBeforeClass() {
		// TODO add setup code.
	}

	/**
	 *
	 * @see com.lodogame.ldsg.service.GoldSetService#getByPayAmount(double)
	 */
	@Test
	public void getByPayAmount() {
		
	}

	
}
