/**
 * This class has been generated by Fast Code Eclipse Plugin 
 * For more information please go to http://fast-code.sourceforge.net/
 * @author : jacky
 * Created : 06/08/2013
 */

package com.lodogame.ldsg.service;

import static org.testng.Assert.assertNotNull;

import java.util.ArrayList;
import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.testng.AbstractTestNGSpringContextTests;
import org.testng.annotations.Test;

import com.lodogame.game.dao.UserHeroDao;
import com.lodogame.ldsg.event.Event;
import com.lodogame.ldsg.event.EventHandle;

@ContextConfiguration(locations = { "classpath:applicationContext-test.xml" })
public class HeroServiceTest extends AbstractTestNGSpringContextTests {

	@Autowired
	public HeroService heroService;

	@Autowired
	private UserHeroDao userHeroDao;

	/**
	 * 
	 * @see com.lodogame.ldsg.service.HeroService#addUserHero(String,String,int,int)
	 */
	@Test
	public void addUserHero() {

	}

	/**
	 * 
	 * @see com.lodogame.ldsg.service.HeroService#changePos(String,String,int,EventHandle)
	 */
	@Test
	public void changePos() {
		boolean result = heroService.changePos("10da636e2fe646c79b0635e93dfdc656", "89926a01ac2d4b5b820c067c4fb74d07", 1, new EventHandle() {

			@Override
			public boolean handle(Event event) {
				return true;
			}
		});
		assertNotNull(result, "result cannot be null");
	}

	@Test
	public void checkContractTransform() {
		// heroService.contractTransform("711615315fbd495a84bebb3f6f0d01da",
		// "0f1e35728688486382df1fd1759762ee");
	}

	@Test
	public void checkHeroTransform() {
		List<String> uhids = new ArrayList<String>();
		uhids.add("05a0451074ac41828d22d1d60ab1fbb1");
		uhids.add("05ee51aede86485dbb96c22a39bd97e9");
		uhids.add("065ac70e7ba34fe1806f28760293ab97");

		// heroService.heroTransform("711615315fbd495a84bebb3f6f0d01da",
		// "03d10beab4a14b11a01bbade69c193cf", uhids);
	}

	@Test
	public void inheritTestt() {
		// String givingHeroId = "36c1ec0f9c8648f79a9bba34ce22f0cd";
		// String inheritHeroId = "41e4e95324c74d2e9153efe2d4f72b39";
		// String uid = "78449f8a35dc4f779dc2cd895ae158f3";
		// heroService.inherit(uid, givingHeroId, inheritHeroId, 0);
		// heroService.inheritPre(uid, givingHeroId, inheritHeroId, 0);

	}

}
