/**
 * This class has been generated by Fast Code Eclipse Plugin 
 * For more information please go to http://fast-code.sourceforge.net/
 * @author : jacky
 * Created : 05/15/2013
 */

package com.lodogame.ldsg.service;

import java.math.BigDecimal;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.testng.AbstractTestNGSpringContextTests;
import org.testng.annotations.Test;

import com.lodogame.game.utils.IDGenerator;

@ContextConfiguration(locations = { "classpath:applicationContext-test.xml" })
public class PaymentServiceTest extends AbstractTestNGSpringContextTests {

	@Autowired
	private GameApiService gameApiService;

	String partnerId = "5001";
	String serverId = "s1";
	String partnerUserId = "81c89f17d7ab45f88392759724324afb";
	String channel = "alipay";
	String orderId = IDGenerator.getID();
	BigDecimal amount = new BigDecimal("2000");
	int gold = 20000;
	String userIp = "192.168.1.6";
	String remark = "remark";

	/**
	 * 
	 * @see com.lodogame.ldsg.service.PaymentService#doPayment(String,int,String,String,String,int,int,String,String)
	 */
	@Test
	public void doPayment() {

	}

}
