/**
 * This class has been generated by Fast Code Eclipse Plugin 
 * For more information please go to http://fast-code.sourceforge.net/
 * @author : jacky
 * Created : 05/17/2013
 */

package com.lodogame.game.dao.impl.mysql;

import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.testng.AbstractTestNGSpringContextTests;
import org.testng.annotations.Test;

@ContextConfiguration(locations = { "classpath:applicationContext-test.xml" })
public class PackageInfoDaoMysqlImplTest extends AbstractTestNGSpringContextTests {

	// F@Autowired
	// private PackageInfoDao packageInfoDao;

	/**
	 * 
	 * @see com.lodogame.ldsg.web.dao.PackageInfoDaoMysqlImpl#getLast()
	 */
	@Test
	public void getLast(int pkgType) {
		// packageInfoDao.getLast(pkgType, "1001");
	}

}
