/**
 * This class has been generated by Fast Code Eclipse Plugin 
 * For more information please go to http://fast-code.sourceforge.net/
 * @author : chenjian
 * Created : 10/04/2013
 */

package com.lodogame.game.dao.impl.mysql;

import java.sql.Date;

import org.testng.annotations.Test;

public class PaymentLogDaoMysqlImplTest {

	/**
	 * 
	 * @see com.lodogame.game.dao.impl.mysql.PaymentLogDaoMysqlImpl#getPaymenList(String,Date,Date,int,int)
	 */
	@Test
	public void getPaymenList() {
		// Date startTime = new Date();
		// Date endTime = new Date();
		// List<PaymentLog> paymenlist =
		// paymentLogDaoMysqlImpl.getPaymenList("",startTime,endTime,1,1);
		// assertNotNull(paymenlist, "paymenlist cannot be null");
	}

}
