/**
 * This class has been generated by Fast Code Eclipse Plugin 
 * For more information please go to http://fast-code.sourceforge.net/
 * @author : jacky
 * Created : 08/23/2013
 */

package com.lodogame.game.dao.impl.mysql;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.testng.AbstractTestNGSpringContextTests;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;

import com.lodogame.model.SystemVipLevel;

@ContextConfiguration(locations = { "classpath:applicationContext-test.xml" })
public class SystemVipLevelDaoMysqlImplTest extends AbstractTestNGSpringContextTests {

	@Autowired
	private SystemVipLevelDaoMysqlImpl systemVipLevelDaoMysqlImpl;

	@BeforeClass
	public void setUpBeforeClass() {
		// TODO add setup code.
	}

	/**
	 * 
	 * @see com.lodogame.game.dao.impl.mysql.SystemVipLevelDaoMysqlImpl#getBuyMoney(int)
	 */
	@Test
	public void getBuyMoney() {
		SystemVipLevel systemVipLevel = systemVipLevelDaoMysqlImpl.getBuyMoney(50);
		System.out.println(systemVipLevel.getVipLevel());
	}

}
