/**
 * This class has been generated by Fast Code Eclipse Plugin 
 * For more information please go to http://fast-code.sourceforge.net/
 * @author : jacky
 * Created : 07/22/2013
 */

package com.lodogame.game.dao.impl.mysql;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.testng.AbstractTestNGSpringContextTests;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;

@ContextConfiguration(locations = { "classpath:applicationContext-test.xml" })
public class UserDailyGainLogDaoMysqlImplTest extends AbstractTestNGSpringContextTests {

	@Autowired
	UserDailyGainLogDaoMysqlImpl userDailyGainLogDaoMysqlImpl;

	@BeforeClass
	public void setUpBeforeClass() {
		// TODO add setup code.
	}

	private String userId = "10da636e2fe646c79b0635e93dfdc656";

	/**
	 * 
	 * @see com.lodogame.game.dao.impl.mysql.UserDailyGainLogDaoMysqlImpl#getUserDailyGain(String,int)
	 */
	@Test
	public void getUserDailyGain() {
		int amount = userDailyGainLogDaoMysqlImpl.getUserDailyGain(userId, 1);
		System.out.println(amount);
	}

	/**
	 * 
	 * @see com.lodogame.game.dao.impl.mysql.UserDailyGainLogDaoMysqlImpl#addUserDailyGain(String,int,int)
	 */
	@Test
	public void addUserDailyGain() {
		userDailyGainLogDaoMysqlImpl.addUserDailyGain(userId, 1, 100);
	}

}
