/**
 * This class has been generated by Fast Code Eclipse Plugin 
 * For more information please go to http://fast-code.sourceforge.net/
 * @author : jacky
 * Created : 06/13/2013
 */

package com.lodogame.game.dao.impl.mysql;

import java.util.Date;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.testng.AbstractTestNGSpringContextTests;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;

import com.lodogame.game.dao.UserOnlineLogDao;
import com.lodogame.game.utils.DateUtils;
import com.lodogame.game.utils.TableUtils;
import com.lodogame.model.UserOnlineLog;

@ContextConfiguration(locations = { "classpath:applicationContext-test.xml" })
public class UserOnlineLogDaoMysqlImplTest extends AbstractTestNGSpringContextTests {

	String userId = "1085d7bf3cd74d0db3c70d2e7a5052e0";

	@Autowired
	private UserOnlineLogDao userOnlineLogDao;

	@BeforeClass
	public void setUpBeforeClass() {
		// TODO add setup code.
	}

	/**
	 * 
	 * @see com.lodogame.game.dao.impl.mysql.UserOnlineLogDaoMysqlImpl#getUserOnline(String)
	 */
	@Test
	public void getUserOnline() {
		long online = userOnlineLogDao.getUserOnline(userId, new Date());
		System.out.println(online);
	}

	/**
	 * 
	 * @see com.lodogame.game.dao.impl.mysql.UserOnlineLogDaoMysqlImpl#add(UserOnlineLog)
	 */
	@Test
	public void add() {
		UserOnlineLog userOnlineLog = new UserOnlineLog();
		userOnlineLog.setUserId(userId);
		userOnlineLog.setLoginTime(new Date());
		userOnlineLog.setLogoutTime(new Date());
		userOnlineLog.setUserIp("127.0.0.1");

		this.userOnlineLogDao.add(userOnlineLog);
	}

	/**
	 * 
	 * @see com.lodogame.game.dao.impl.mysql.UserOnlineLogDaoMysqlImpl#isLogin(String,Date)
	 */
	@Test
	public void isLogin() {
		boolean t = this.userOnlineLogDao.isLogin("46d8ea13e3cc4d4296a0ca6bbb3ecc2d", DateUtils.addDays(new Date(), 1));
		System.out.println(t);
	}
	
	@Test
	public void getLastOnlineTest() {
		
		String userId = "00b9d493516249b9ac8a3b5b4a546aa7";
		String date = new Date().toLocaleString();
		long time = userOnlineLogDao.getLastOnline(userId);
		
		long currentTimeMillis = System.currentTimeMillis();
		System.out.println(currentTimeMillis);
		System.out.println(time);
	}
	
	@Test
	public void getUserOnlineTest() {
		String userId = "5b682917bba04a96a2231bd5d19846a1";
		String table = TableUtils.getUserOnlineLogTable(userId);
		System.out.println(table);

	}

}
