/**
 * This class has been generated by Fast Code Eclipse Plugin 
 * For more information please go to http://fast-code.sourceforge.net/
 * @author : jacky
 * Created : 05/23/2013
 */

package com.lodogame.game.dao.impl.mysql;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.testng.annotations.Test;

@ContextConfiguration(locations = { "classpath:applicationContext-test.xml" })
public class UserToolDaoMysqlImplTest {

	private String userId = "000000000000000000000000000066";

	@Autowired
	private UserToolDaoMysqlImpl userToolDaoMysqlImpl;

	/**
	 * 
	 * @see com.lodogame.game.dao.impl.mysql.UserToolDaoMysqlImpl#reduceUserTool(String,int,int)
	 */
	@Test
	public void reduceUserTool() {
		// userToolDaoMysqlImpl
	}

}
