/**
 * This class has been generated by Fast Code Eclipse Plugin 
 * For more information please go to http://fast-code.sourceforge.net/
 * @author : jacky
 * Created : 08/17/2013
 */

package com.lodogame.ldsg.service.impl;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.testng.AbstractTestNGSpringContextTests;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;

import com.lodogame.ldsg.event.Event;
import com.lodogame.ldsg.event.EventHandle;
import com.lodogame.ldsg.service.ActivityService;

@ContextConfiguration(locations = { "classpath:applicationContext-test.xml" })
public class ActivityServiceImplTest extends AbstractTestNGSpringContextTests {

	@Autowired
	private ActivityService activityService;

	@BeforeClass
	public void setUpBeforeClass() {
		// TODO add setup code.
	}

	/**
	 * 
	 * @see com.lodogame.ldsg.service.impl.ActivityServiceImpl#getSystemHeroExchangeBOList(int)
	 */
	@Test
	public void getSystemHeroExchangeBOList() {
		
	}

	/**
	 * 
	 * @see com.lodogame.ldsg.service.impl.ActivityServiceImpl#receiveGiftCodeGiftBag(String,String,EventHandle)
	 */
	@Test
	public void receiveGiftCodeGiftBag() {
		this.activityService.receiveGiftCodeGiftBag("", "123", new EventHandle() {

			@Override
			public boolean handle(Event event) {
				// TODO Auto-generated method stub
				return false;
			}
		});
	}

	@Test
	public void getloginRewardTest() {
		// String userId = "00053c430878446da75f9d5aec894ee1";
		// activityService.getLoginReward(userId);
	}

	@Test
	public void getLoginRewardListTest() {
		// String userId = "00053c430878446da75f9d5aec894ee1";
		// activityService.getLoginRewardList(userId);
	}
	
	@Test
	public void getUserLoginRewardList() {
		String userId = "7291d80e51d44ffa8ff2876c591bfc18";
		activityService.getLoginRewardList(userId);
	}
}
