/**
 * This class has been generated by Fast Code Eclipse Plugin 
 * For more information please go to http://fast-code.sourceforge.net/
 * @author : jacky
 * Created : 05/22/2013
 */

package com.lodogame.ldsg.service.impl;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.testng.AbstractTestNGSpringContextTests;
import org.testng.annotations.Test;

import com.lodogame.ldsg.bo.SystemGoldSetBO;
import com.lodogame.ldsg.service.GoldSetService;
import com.lodogame.model.SystemGoldSet;

@ContextConfiguration(locations = { "classpath:applicationContext-test.xml" })
public class GoldSetServiceImplTest extends AbstractTestNGSpringContextTests {

	@Autowired
	private GoldSetService godSetService;

	/**
	 * 
	 * @see com.lodogame.ldsg.service.impl.GoldSetServiceImpl#getGoldSetList()
	 */
	@Test
	public void getGoldSetList() {

		List<SystemGoldSetBO> boList = godSetService.getGoldSetList();
		for (SystemGoldSetBO bo : boList) {

			System.out.println(bo.getTitle() + "|" + bo.getDescription() + "|" + bo.getMoney());

		}
	}

	@Test
	public void getByPayAmount() {
		SystemGoldSet systemGoldSet = this.godSetService.getByPayAmount(1000);
		System.out.println(systemGoldSet.getGold());
	}
}
