/**
 * This class has been generated by Fast Code Eclipse Plugin 
 * For more information please go to http://fast-code.sourceforge.net/
 * @author : jacky
 * Created : 05/17/2013
 */

package com.lodogame.ldsg.service.impl;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.testng.AbstractTestNGSpringContextTests;
import org.testng.annotations.Test;

import com.lodogame.game.dao.UserDao;
import com.lodogame.game.utils.IDGenerator;
import com.lodogame.ldsg.bo.CommonDropBO;
import com.lodogame.ldsg.constants.ToolUseType;
import com.lodogame.ldsg.service.HeroService;
import com.lodogame.model.User;

@ContextConfiguration(locations = { "classpath:applicationContext-test.xml" })
public class HeroServiceImplTest extends AbstractTestNGSpringContextTests {

	String userId = "49ff94dbe9ac4b3f953a1870718cb32b";

	@Autowired
	private HeroService heroService;

	@Autowired
	private UserDao userDao;

	/**
	 * 
	 * @see com.lodogame.ldsg.service.impl.HeroServiceImpl#getUserHeroBO(String)
	 */
	@Test
	public void getUserHeroBO() {

		// List<BattleHeroBO> list =
		// this.heroService.getUserBattleHeroBOList("b661c63b7dbc433d8622bcba35838a6a");
		//
		// for (BattleHeroBO bo : list) {
		// System.out.println(bo.getLife());
		// }
		heroService.addUserHero(userId, IDGenerator.getID(), 1, 0, 0);

	}

	@Test
	public void lightNodeTest() {
		String userId = "8d54d08e93c34a7c8ece44db6d86f254";
		String userHeroId = "05449321a0994cd4985dba802469d280";
		int nodeId = 104;
		int type = 2;
		heroService.lightNode(userId, userHeroId, nodeId, type);
	}

	@Test
	public void upgradeTest() {
		String userId = "41e6eef2836d476295b5eec1ae7ced6e";
		String userHeroId = "cedb4f7e578d46b8bf8c51a5d3277c27";
		heroService.upgrade(userId, userHeroId);
	}

	@Test
	public void addUserHero() {
		List<User> users = userDao.getAllUser();

		for (User user : users) {
			heroService.addUserHero(user.getUserId(), IDGenerator.getID(), 1, 1, ToolUseType.ADD_ACTIVITY_DRAW);
		}

	}

	@Test
	public void mergeTest() {
		String uid = "8d54d08e93c34a7c8ece44db6d86f254";
		CommonDropBO dr = heroService.merge(uid, 50001);
		System.out.println(dr);
	}
	
}
