/**
 * This class has been generated by Fast Code Eclipse Plugin 
 * For more information please go to http://fast-code.sourceforge.net/
 * @author : jacky
 * Created : 10/31/2013
 */

package com.lodogame.ldsg.service.impl;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.testng.AbstractTestNGSpringContextTests;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;

import com.lodogame.ldsg.service.MailService;

@ContextConfiguration(locations = { "classpath:applicationContext-test.xml" })
public class MailServiceImplTest extends AbstractTestNGSpringContextTests {

	@Autowired
	private MailService mailService;

	@BeforeClass
	public void setUpBeforeClass() {
		// TODO add setup code.
	}

	/**
	 * 
	 * @see com.lodogame.ldsg.service.impl.MailServiceImpl#send(String,String,String,int,String)
	 */
	@Test
	public void send() {

//		 mailService.send("测试",
//		 "十八届三中全会召开在即，人们都在期盼会议释放出正能量。回顾改革开放以来的每一次三中全会，都有力地促进了中国经济发展与社会进步。这次全会能否给转型升级的中国经济社会带来新机遇？是衡量这次会议成功与否的重要标志！如何激发经济新动力，破解社会难题，建设美丽中国，构建开明政治，应是重点",
//		 "1,1,100|2,2,100000|3001,68,1|2001,104001,1|", 1, "", 100000, new Date(), "");

	}
	
	@Test
	public void needMailTest() {
		
	}
}
