/**
 * This class has been generated by Fast Code Eclipse Plugin 
 * For more information please go to http://fast-code.sourceforge.net/
 * @author : jacky
 * Created : 06/08/2013
 */

package com.lodogame.ldsg.service.impl;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.testng.AbstractTestNGSpringContextTests;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;

@ContextConfiguration(locations = { "classpath:applicationContext-test.xml" })
public class MessageServiceImplTest extends AbstractTestNGSpringContextTests {

	@Autowired
	private MessageServiceImpl messageServiceImpl;

	@BeforeClass
	public void setUpBeforeClass() {
		// TODO add setup code.
	}

	/**
	 * 
	 * @see com.lodogame.ldsg.service.impl.MessageServiceImpl#sendGainHeroMsg(String,String)
	 */
	@Test
	public void sendGainHeroMsg() {

		messageServiceImpl.sendGainHeroMsg("", "测试用户", "吕布", 4, "xx");
	}

	/**
	 * 
	 * @see com.lodogame.ldsg.service.impl.MessageServiceImpl#sendSystemMsg(String)
	 */
	@Test
	public void sendSystemMsg() {
		messageServiceImpl.sendSystemMsg("测试 -1 ");
		messageServiceImpl.sendSystemMsg("测试 -2 ");
		messageServiceImpl.sendSystemMsg("测试 -3 ");

	}

	/**
	 * 
	 * @see com.lodogame.ldsg.service.impl.MessageServiceImpl#sendPkMsg(String)
	 */
	@Test
	public void sendPkMsg() {
		// messageServiceImpl.sendPkMsg("", "000");
	}

}
