/**
 * This class has been generated by Fast Code Eclipse Plugin 
 * For more information please go to http://fast-code.sourceforge.net/
 * @author : jacky
 * Created : 08/17/2013
 */

package com.lodogame.ldsg.service.impl;

import org.springframework.test.context.testng.AbstractTestNGSpringContextTests;

public class RankServiceImplTest extends AbstractTestNGSpringContextTests {


}
