/**
 * This class has been generated by Fast Code Eclipse Plugin 
 * For more information please go to http://fast-code.sourceforge.net/
 * @author : jacky
 * Created : 06/14/2013
 */

package com.lodogame.game.dao;

import org.springframework.test.context.ContextConfiguration;
import org.testng.annotations.Test;

@ContextConfiguration(locations = { "classpath:applicationContext-test.xml" })
public class TavernDropToolDaoTest {

	/**
	 * 
	 * @see com.lodogame.game.dao.TavernDropToolDao#getTavernDropToolList(int)
	 */
	@Test
	public void getTavernDropToolList() {

	}

}
