/**
 * This class has been generated by Fast Code Eclipse Plugin 
 * For more information please go to http://fast-code.sourceforge.net/
 * @author : jacky
 * Created : 05/29/2013
 */

package com.lodogame.game.dao.impl.cache;

import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.testng.AbstractTestNGSpringContextTests;
import org.testng.annotations.Test;

@ContextConfiguration(locations = { "classpath:applicationContext-test.xml" })
public class SystemTaskDaoCacheImplTest extends AbstractTestNGSpringContextTests {

	/**
	 * 
	 * @see com.lodogame.game.dao.impl.cache.SystemTaskDaoCacheImpl#getTaskList(int)
	 */
	@Test
	public void getTaskList() {
		// List<SystemTask> taskList = systemTaskDao.getTaskList(0);
		// for (SystemTask task : taskList) {
		// System.out.println(task.getTaskName());
		// }
	}

}
