/**
 * This class has been generated by Fast Code Eclipse Plugin 
 * For more information please go to http://fast-code.sourceforge.net/
 * @author : jacky
 * Created : 05/28/2013
 */

package com.lodogame.game.dao.impl.cache;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.testng.AbstractTestNGSpringContextTests;
import org.testng.annotations.Test;

import com.lodogame.game.dao.SystemForcesMonsterDao;
import com.lodogame.model.SystemForcesMonster;

@ContextConfiguration(locations = { "classpath:applicationContext-test.xml" })
public class SystemForcesMonsterDaoCacheImplTest extends AbstractTestNGSpringContextTests {

	@Autowired
	private SystemForcesMonsterDao systemForcesMonsterDao;

	@Test
	public void getForcesMonsterList() {
		List<SystemForcesMonster> list = systemForcesMonsterDao.getForcesMonsterList(103);
		for (SystemForcesMonster systemForcesMonster : list) {
			System.out.println(systemForcesMonster.getMonsterName());
		}
	}
}
