/**
 * This class has been generated by Fast Code Eclipse Plugin 
 * For more information please go to http://fast-code.sourceforge.net/
 * @author : jacky
 * Created : 05/29/2013
 */

package com.lodogame.game.dao.impl.cache;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.testng.AbstractTestNGSpringContextTests;
import org.testng.annotations.Test;

import com.lodogame.game.dao.UserDailyTaskDao;

@ContextConfiguration(locations = { "classpath:applicationContext-test.xml" })
public class SystemDailyTaskDaoCacheImplTest extends AbstractTestNGSpringContextTests {

	@Autowired
	private UserDailyTaskDao userDailyTaskDao;
	
	/**
	 * 
	 * @see com.lodogame.game.dao.impl.cache.SystemTaskDaoCacheImpl#getTaskList(int)
	 */
	@Test
	public void getTaskList() {
		System.out.println(userDailyTaskDao);
	}

}
